entenna:
  build: .
  environment:
    - MONGO_URL=mongodb://mongodb/entenna
    - ROOT_URL=http://127.0.0.1
    - PORT=3000
  links:
    - mongodb
  ports:
    - "80:3000"

mongodb:
   image: mongo
   ports:
     - 27017


